backend:
  name: github
  branch: main
  repo: serbia70/astro-paper-DecapCMS
  site_domain: astro-paper-decapcms.vercel.app
  base_url: https://astro-paper-decapcms.vercel.app/
  auth_endpoint: oauth

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview_path_date_field: "date"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "作者", name: "Author", widget: "string", required: false }
      - { label: "精选", name: "featured", widget: "boolean", required: false }
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "图像", name: "img", widget: "image", required: false}
      - { label: "发布日期", name: "pubDatetime", widget: "datetime" }
      - { label: "更新日期", name: "modDatetime", widget: "datetime", required: false}
      - { label: "标题", name: "title", widget: "string" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "描述", name: "description" }
      - { label: "Body", name: "body", widget: "markdown" }
